SELECT * FROM MEMBER;

DECLARE
    V_NAME  VARCHAR2(25);
    V_JIKWI VARCHAR2(10);
    V_SAL   NUMBER;
    CURSOR MY_CORSOR IS 
    SELECT NAME, JIKWI, SAL FROM MEMBER
    ORDER BY SAL DESC;
BEGIN
    OPEN MY_CORSOR;
    LOOP
        FETCH MY_CORSOR INTO V_NAME, V_JIKWI, V_SAL;
        EXIT WHEN MY_CORSOR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_NAME || ' works on ' || V_JIKWI || ', earns $' || V_SAL || ' per month.');
    END LOOP;
    CLOSE MY_CORSOR;
END;