CREATE TABLE TEST3
(
    ID      NUMBER,
    NAME    VARCHAR2(10)
)

INSERT INTO TEST3 VALUES(1, '홍길동');
INSERT INTO TEST3 VALUES(2, '이순신');
COMMIT;

SELECT * FROM TEST3 WHERE ID = 1;
SELECT * FROM TEST3;
--기본키 지정
ALTER TABLE TEST3 ADD CONSTRAINT PK_TEST3 PRIMARY KEY(ID);

--인덱스 확인
SELECT * FROM USER_INDEXES WHERE TABLE_NAME = 'TEST3';

--인덱스 생성
SELECT * FROM TEST3 WHERE NAME = '홍길동';
CREATE INDEX ix_test3_name on TEST3(NAME);
    