CREATE TABLE TEACHER (
    CODE    INT PRIMARY KEY,
    SUBJECT VARCHAR2(15),
    NAME    VARCHAR2(15)
);

INSERT INTO TEACHER VALUES(1,'국어', '세종대왕');
INSERT INTO TEACHER VALUES(2,'수학', '가우스');
INSERT INTO TEACHER VALUES(3,'영어', '앙겔른');
COMMIT;

SELECT * FROM TEACHER;
DELETE FROM TEACHER WHERE CODE =3;
DELETE FROM TEACHER;
ROLLBACK;

INSERT INTO TEACHER VALUES(4,'물리', '뉴턴');
SAVEPOINT a;
INSERT INTO TEACHER VALUES(5,'경제', '스미스');
INSERT INTO TEACHER VALUES(6,'화학', '헬렌');
ROLLBACK TO a;
